version: '3'
services:
    fe:
        build:
            context: ./fe
        ports:
            - '3000:80'
        # ports:
        #     - '80:80'
        networks:
            - my_network
    be:
        build:
            context: ./be
        ports:
            - '8080:8080'
        networks:
            - my_network
        depends_on:
            - pe-db
            - pe-redis
    pe-db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: pe_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - '3309:3306'
        volumes:
            - D:/4. Software Development/Database/pe-management-db-backup:/var/lib/mysql
        networks:
            - my_network
    pe-redis:
        image: redis:5.0
        ports:
            - '6379:6379'
        networks:
            - my_network
networks:
    my_network:
